### ISSUE TITLE
获取对象类型 章节的小问题

### ISSUE THREAD

**Issue by yulingtianxia** [swifter-tips/Public-Issues#18]
```
let date = NSDate()
let name = NSStringFromClass(objc_getClass(date))
println(name)
```

我发现`objc_getClass`方法参数类型是`UnsafePointer<Int8>`，返回类型是`AnyObject!`,于是上面这段代码会出错。  
感觉在Swift中施展Objective Runtime的确挺考验人的，喵大大加油！

**Comment by onevcat** [comment]
最主要还是天天变- -这点很讨厌

**Comment by yulingtianxia** [comment]
是啊，喵大大辛苦啦，等下个Swift大版本更新后一起解决吧，说不定到时候又改了呢。  
估计大部分读者都不会看的太仔细，我是纯属刚考完试闲来无事学学姿势

**Comment by onevcat** [comment]
Resolved
