### ISSUE TITLE
Tip3 Page37

### ISSUE THREAD

**Issue by Onetaway** [swifter-tips/Public-Issues#2]
struct MyCar: Vehicle里第2行

var color = UIColor.blueColor()!
加感叹号playground不过，应该去掉感叹号

**Comment by onevcat** [comment]
Thanks. 应该是 1.0 的 Apple 的 API 调整造成的。

**Comment by onevcat** [comment]
等到更新修正后再关闭吧..

**Comment by onevcat** [comment]
已修正
