### ISSUE TITLE
typealias 和泛型接口，可能的表述问题：第一段的表述，“省下脑细胞”那句话的表述

### ISSUE THREAD

**Issue by nixzhu** [swifter-tips/Public-Issues#29]
第一段：typealias 可为已经存在的类型定义别名。通过定义别名，可使代码变得更加清晰。它的使用语法也很简单，写起来类似定义普通的变量并赋值的语句。比如……
（文中还有不少地方有“某某是用来做…的”这样的句式，建议一并改去）

省下脑细胞段：……，若你可以不再关心……Int 或者 String 等基本类型到底代表的是什么，一定会省下……

**Comment by onevcat** [comment]
fixed
