### ISSUE TITLE
Tip Sequence

### ISSUE THREAD

**Issue by Onetaway** [swifter-tips/Public-Issues#3]
估计1.0改了不少的说。。
class ReverseGenerator: GeneratorType

error: reference to generic type 'GeneratorSequence' requires arguments in <...>
class ReverseGenerator: GeneratorSequence {
                                        ^

**Comment by onevcat** [comment]
我这里似乎没有问题，请问下你的环境？

**Comment by onevcat** [comment]
class ReverseGenerator: GeneratorType {

嗷- -应该是你那边敲错了 `GeneratorType` 而不是 `GeneratorSequence`
