### ISSUE TITLE
Tip: GCD 和延时调用

### ISSUE THREAD

**Issue by dopcn** [swifter-tips/Public-Issues#32]
原文提到：

> 因为在 iOS 8 中 GCD 得 到了惊人的进化,现在加入了存储一个 block 的要素 dispatch_block_t,于是我们可以 很容易去取消一个正在等待执行的 block 了。

根据文档

> typealias dispatch_block_t = () -> Void
> ...
> Available in iOS 4.0 and later.

有出入

 GCD 在 iOS 8 中的更新似乎只有 priority 相关常量重命名为 quality of service 风格，「惊人的进化」是指？

另外发行的电子书的更新是怎么进行的？我获得的下载链接显示是5个月以前的版本，购买渠道是 selfstore

**Comment by onevcat** [comment]
这里想说的是 `dispatch_cancel`，新版本中会注意修正一下。

电子书最近没有更新，有更新的话应该会通过邮件有通知，另外也可以到[这里](https://selfstore.io/products/171/posts)查看版本信息。

**Comment by dopcn** [comment]
:clap:
