### ISSUE TITLE
Gumroad App 里的排版问题

### ISSUE THREAD

**Issue by lexrus** [swifter-tips/Public-Issues#38]
可能是 Gumroad App 的问题，头尾都有很多空白。

![img_0166](https://cloud.githubusercontent.com/assets/219689/9485222/04f6b47a-4be9-11e5-9467-512daea7e180.PNG)

**Comment by onevcat** [comment]
似乎在其他版本中没有发现类似情况。先关掉了，如果在其他阅读器中出现的话在考虑如何解决了..

**Comment by lexrus** [comment]
恩，关掉吧。目前看来不会有什么人用 Gumroad 官方的 App 看电子书的，排版和操作都有问题。
