### ISSUE TITLE
Xcode Beta 6 中的代码变化

### ISSUE THREAD

**Issue by thoamsy** [swifter-tips/Public-Issues#39]
虽然 advance 方法被重命名为 advancedBy，但是使用方法同时也改变了。
let s = “abcdef”
s.startIndex.advancedBy(2)
或者
s.endIndex.advancedBy(-3)
现在变成这样调用了，就相当与调用几个 successor() 或者 processor()
希望修改一下 NSString 那一章的相关内容

**Comment by thoamsy** [comment]
可以在文中建议读者去 Apple 开发者网站下载一个标准库的 playground，里面有更详细的关于 string 的实例 https://developer.apple.com/swift/resources/

**Comment by onevcat** [comment]
2.0 版本中已经修正为 `advancedBy`

**Comment by thoamsy** [comment]
可是这样会编译是通不过的,  s.advancedBy() 这种用法是不对

**Comment by onevcat** [comment]
可以说明一下书里示例代码的哪一句编译通不过么？谢谢
