### ISSUE TITLE
.mobi 格式在kindle 上字体颜色偏白（太淡）

### ISSUE THREAD

**Issue by ghost** [swifter-tips/Public-Issues#40]
swifter tips 最新版本（2.0.1）在我的 kindle 设备(vk)上显式效果见附件。

照片上看着不是很明显，但实际阅读感觉 **字体** 太白（太淡），眼睛很受罪，能稍微调的暗点就好了。

<img width="488" alt="screen shot 2015-08-28 at 9 04 50 am" src="https://cloud.githubusercontent.com/assets/12506413/9536971/3e78d85e-4d65-11e5-8d0d-415571f9d0c5.png">

**Comment by onevcat** [comment]
应该在 2.0.2 中修正，近期会发布。

**Comment by onevcat** [comment]
已发布。
