### ISSUE TITLE
Struct Mutable 报错信息更正

### ISSUE THREAD

**Issue by ihomway** [swifter-tips/Public-Issues#51]
使用环境 Mac OS X 10.11，Xcode 7 下，错误信息已经更正为："Left side of mutating operator isn't mutable: 'self' is immutable"
<img width="592" alt="untitled" src="https://cloud.githubusercontent.com/assets/9472797/10533136/0c996efc-73f8-11e5-9285-1b9dc24a20ad.png">

**Comment by onevcat** [comment]
Fixed. I will update the book later.
