### ISSUE TITLE
print(num.0.0.0.0.0.0.0.0.0.0) doesn't work

### ISSUE THREAD

**Issue by ihomway** [swifter-tips/Public-Issues#52]
Tuple 中的  `print(num.0.0.0.0.0.0.0.0.0.0)` 无法使用
<img width="620" alt="untitled" src="https://cloud.githubusercontent.com/assets/9472797/10534419/ebe6c67e-740a-11e5-98b6-f0e7987e69d5.png">

**Comment by onevcat** [comment]
新版的书中已经更正了，请更新。

**Comment by ihomway** [comment]
3ku
