### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by numbbbbb** [swifter-tips/Public-Issues#55]
阅读过程中发现了一些错别字，整理如下：

| 页数 | 内容 |
| :-: | :-: |
| 64 | “具有条例”→“具有条理” |
| 69 | “可能回写类似这样的代码”→“可能会写类似这样的代码” |
| 89 | “举个一个简单的使用例子”：“个”和“一个”重复 |
| 129 | “申明变量”→“声明变量” |
| 137 | “不可能保证一尘不变”→“不可能保证一成不变” |
| 148 | “已提供一个判等为真时”→“以提供一个判等为真时” |
| 159 | “并没有直接的源生类型”→“并没有直接的原生类型” |
| 184 | “Apple 为什么语言引入了异常机制”→“Apple 为这这门语言引入了异常机制” |
| 189 | “这样在不是灵活性的同时”→“这样在不失灵活性的同时” |
| 199 | “GCD 和延时调用”链接后少了空格（或者链接前多了空格） |
| 202 | “依赖关系对于人来收”→“依赖关系对于人来说”  “才能最终架立起一套可用的环境”→“才能最终建立起一套可用的环境” |
| 233 | “如果我们不知道等差数列求和公示”→“如果我们不知道等差数列求和公式” |

我阅读的是**2.0.2（2015 年 9 月 19 日）** PDF 版

**Comment by onevcat** [comment]
已经修正，将于近期更新，十分感谢！
