### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by leibaozai** [swifter-tips/Public-Issues#59]
42页    在声明方法是就指定第一个参数为一个字符串——> 在声明方法“时”(是)就指定第一个参数为一个字符串

44页    在Swift中let声明的值是不变量，无法被写入赋值，这对于构建线程安全的API十分有用。而因为Swift的init只可能被调用一次，因此在init中我们可以为不变量进行赋值——> 在Swift中let声明的值是不可变量，无法被写入赋值，这对于构建线程安全的API来说十分有用。又因为Swift的init只可能被调用一次，因此在init中我们可以为不可变量进行赋值（Ps:个人观点）

45页    因此进行一下总结——> 因此进行以下总结

**Comment by onevcat** [comment]
感谢提出，在之后进行校正修改。

**Comment by leibaozai** [comment]
113页 笔者已经像Apple提交了bug报告—向(像)

**Comment by onevcat** [comment]
已经修正，过一阵子更新
