### ISSUE TITLE
错字

### ISSUE THREAD

**Issue by toearth** [swifter-tips/Public-Issues#66]
“COpaquePointer 在 Swift 中扮演的是指针转换的中间人的角色，我们可以通过这个类型在不同指针类型_减_进行转换”

摘录来自: 王巍 (onevcat). “Swifter - Swift 必备 Tips (第三版).” GitBook. iBooks. 
此材料受版权保护。

**Comment by onevcat** [comment]
Fixed and will release later. Thanks!

**Comment by toearth** [comment]
Your book is great，I got a lot. Thanks too
