### ISSUE TITLE
Sequence章节有误

### ISSUE THREAD

**Issue by a5978445** [swifter-tips/Public-Issues#71]
书中代码如下：
  let arr = [0,1,2,3,4]
        for i in ReverseSequence(array: arr) {
            print("Index \(i) is \(arr[i])")
        }

事实上 i 代表的就是元素，而不是索引  print("Index \(i) is \(arr[i])") 违背原意会造成数组越界。
 改成这样： let arr = [0,1,2,3,8]
则提示数组越界。
我用的是xcode8.2 。

**Comment by onevcat** [comment]
并没有说里面是索引...就是举了个例子而已..
