### ISSUE TITLE
Tip 多类型和容器

### ISSUE THREAD

**Issue by Onetaway** [swifter-tips/Public-Issues#8]
```
    let mixed: [Printable] = [1, "two", 3]
```

编译不过。
Printable 没有遵守 StringLiteralConvertable协议

**Comment by onevcat** [comment]
仔细看了一下，这里这个 "two" 被用字符串字面量转换为了 `Selector`。这个例子不是很好，需要考虑进行无误导的重写。

---

需要加上 `import UIKit` 之类的，导入 `Foundation` 框架转成。因为 `String` 只实现了 `DebugPrintable` 而没有实现 `Printable`。

ver 1.0.1 里加上说明。

**Comment by Onetaway** [comment]
恩  多谢大大指点

**Comment by onevcat** [comment]
谢谢您指出这个问题。我之前都没注意到，想当然了。

**Comment by Onetaway** [comment]
哪里哪里  喵大客气了，我也是在学习中

**Comment by onevcat** [comment]
已修正并说明
